### PR TITLE
Some more passing tests, some questions

### PR DESCRIPTION
**Pull request by davidtheclark**
I got a couple more tests to pass, deleted some of the TODO tests that were tightly tied to cssnext. Nothing definitive is done here; it's just some progress.

But I stopped because I ran into a question: I'm not sure how to deal with the test "with an input file that does not exist" — because I don't know how to handle to look for a stdin but then know what to do if there is none. How to tell that the stream is empty and will not be fed?

### CODE REVIEW

**Comment by MoOx** [comment]
Nice. Let me double and I will tell you back.

**Comment by MoOx** [comment]
@davidtheclark I think what you did is great, and I don't think we should bother ourselves with this question. We should just assume that `getStdin` will do his job and give us a stdin via the promise resolution.

**Comment by MoOx** [comment]
Is what I am saying making sense to you?

**Comment by davidtheclark** [comment]
My problem is that I can't get this test to pass:

```js
test.only("with an input file that does not exist", function(t) {
  let planned = 0

  exec(
    `${ cliBin } ${ fixturePath }/nonexistent ` +
    `--verbose`,
    function(err, stdout, stderr) {
      t.ok(
        err && err.code === 1,
        "should return an error when input file is unreadable"
      )
      t.equal(
        stderr.trim(),
        "No input files or stdin to read",
        "shuld show that no input file or stdin was found"
      )
    }
  )
  planned += 2

  t.plan(planned)
})
```

It seems that if there's no stdin, `get-stdin` just hangs indefinitely. I do think it's supposed to be address, though, because of https://github.com/sindresorhus/get-stdin/issues/1. So I'm just confused about this.

**Comment by MoOx** [comment]
The thing is, args like a non existant file are being drop by the glob call. So the module wait for stdin.
I will handle this and raise an error if there is some args (supposed to be input files) but nothing out from the glob call.

**Comment by davidtheclark** [comment]
That makes sense. I think I was just getting stream-confused, which is not uncommon for me.

**Pull request merged**
